from .animal_card import AnimalCardDialog
from .loaded_doalog import LoadedDialog
from .field_settings_dialog import FieldSettingsDialog
from .output_results_dialog import OutputResultsDialog
from .save_image_dialog import SaveImgaeDialog
from .video_trimmer_dialog import VideoTrimmerDialog
from .app_path_settings_dialog import AppPathSettingsDialog
from .theme_language_dialog import ThemeLanguageDialog