# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'settings.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QDoubleSpinBox, QFormLayout, QGridLayout, QGroupBox,
    QLabel, QPushButton, QScrollArea, QSizePolicy,
    QSpacerItem, QSpinBox, QStackedWidget, QTabWidget,
    QWidget)

class Ui_settings(object):
    def setupUi(self, settings):
        if not settings.objectName():
            settings.setObjectName(u"settings")
        settings.resize(1066, 570)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(settings.sizePolicy().hasHeightForWidth())
        settings.setSizePolicy(sizePolicy)
        settings.setMinimumSize(QSize(1050, 570))
        settings.setMaximumSize(QSize(1070, 570))
        settings.setStyleSheet(u"QMainWindow {\n"
"    background-color: #e9edf5;\n"
"}\n"
"")
        self.lblImage = QLabel(settings)
        self.lblImage.setObjectName(u"lblImage")
        self.lblImage.setGeometry(QRect(10, 10, 550, 550))
        self.lblImage.setMinimumSize(QSize(550, 550))
        self.lblImage.setStyleSheet(u"background-color: black;")
        self.stackedWidget = QStackedWidget(settings)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(778, 9, 281, 481))
        self.stackedWidget.setMinimumSize(QSize(260, 460))
        self.stackedWidget.setStyleSheet(u"")
        self.pageBox = QWidget()
        self.pageBox.setObjectName(u"pageBox")
        self.groupBox = QGroupBox(self.pageBox)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 261, 281))
        self.lblSmallField = QLabel(self.groupBox)
        self.lblSmallField.setObjectName(u"lblSmallField")
        self.lblSmallField.setGeometry(QRect(10, 30, 100, 40))
        self.lblSmallField.setMinimumSize(QSize(100, 40))
        self.spinb1 = QSpinBox(self.groupBox)
        self.spinb1.setObjectName(u"spinb1")
        self.spinb1.setGeometry(QRect(170, 30, 81, 40))
        self.spinb1.setMinimumSize(QSize(60, 40))
        self.lblMediumField = QLabel(self.groupBox)
        self.lblMediumField.setObjectName(u"lblMediumField")
        self.lblMediumField.setGeometry(QRect(10, 80, 101, 40))
        self.lblMediumField.setMinimumSize(QSize(100, 40))
        self.spinb2 = QSpinBox(self.groupBox)
        self.spinb2.setObjectName(u"spinb2")
        self.spinb2.setGeometry(QRect(170, 80, 81, 40))
        self.spinb2.setMinimumSize(QSize(60, 40))
        self.lblLargeField = QLabel(self.groupBox)
        self.lblLargeField.setObjectName(u"lblLargeField")
        self.lblLargeField.setGeometry(QRect(10, 133, 100, 40))
        self.lblLargeField.setMinimumSize(QSize(100, 40))
        self.spinb3 = QSpinBox(self.groupBox)
        self.spinb3.setObjectName(u"spinb3")
        self.spinb3.setGeometry(QRect(170, 130, 81, 40))
        self.spinb3.setMinimumSize(QSize(60, 40))
        self.sbBOXCountObject = QSpinBox(self.groupBox)
        self.sbBOXCountObject.setObjectName(u"sbBOXCountObject")
        self.sbBOXCountObject.setGeometry(QRect(170, 180, 80, 40))
        self.sbBOXCountObject.setMinimumSize(QSize(80, 40))
        self.sbBOXAreaInt = QSpinBox(self.groupBox)
        self.sbBOXAreaInt.setObjectName(u"sbBOXAreaInt")
        self.sbBOXAreaInt.setGeometry(QRect(170, 230, 80, 40))
        self.sbBOXAreaInt.setMinimumSize(QSize(80, 40))
        self.lblBOXAreaInt = QLabel(self.groupBox)
        self.lblBOXAreaInt.setObjectName(u"lblBOXAreaInt")
        self.lblBOXAreaInt.setGeometry(QRect(10, 230, 161, 40))
        self.lblBOXAreaInt.setMinimumSize(QSize(120, 40))
        self.lblBOXCountObject = QLabel(self.groupBox)
        self.lblBOXCountObject.setObjectName(u"lblBOXCountObject")
        self.lblBOXCountObject.setGeometry(QRect(10, 180, 151, 40))
        self.lblBOXCountObject.setMinimumSize(QSize(120, 40))
        self.stackedWidget.addWidget(self.pageBox)
        self.pageCross = QWidget()
        self.pageCross.setObjectName(u"pageCross")
        self.groupBox_2 = QGroupBox(self.pageCross)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 10, 251, 291))
        self.lblText = QLabel(self.groupBox_2)
        self.lblText.setObjectName(u"lblText")
        self.lblText.setGeometry(QRect(10, 130, 120, 40))
        self.lblText.setMinimumSize(QSize(120, 40))
        self.checkbCenter = QCheckBox(self.groupBox_2)
        self.checkbCenter.setObjectName(u"checkbCenter")
        self.checkbCenter.setGeometry(QRect(160, 130, 80, 40))
        self.checkbCenter.setMinimumSize(QSize(80, 40))
        self.checkbUp = QCheckBox(self.groupBox_2)
        self.checkbUp.setObjectName(u"checkbUp")
        self.checkbUp.setGeometry(QRect(10, 170, 80, 40))
        self.checkbUp.setMinimumSize(QSize(80, 40))
        self.checkbLeft = QCheckBox(self.groupBox_2)
        self.checkbLeft.setObjectName(u"checkbLeft")
        self.checkbLeft.setGeometry(QRect(160, 210, 80, 40))
        self.checkbLeft.setMinimumSize(QSize(80, 40))
        self.checkbRight = QCheckBox(self.groupBox_2)
        self.checkbRight.setObjectName(u"checkbRight")
        self.checkbRight.setGeometry(QRect(160, 170, 80, 40))
        self.checkbRight.setMinimumSize(QSize(80, 40))
        self.checkbDown = QCheckBox(self.groupBox_2)
        self.checkbDown.setObjectName(u"checkbDown")
        self.checkbDown.setGeometry(QRect(10, 214, 80, 40))
        self.checkbDown.setMinimumSize(QSize(80, 40))
        self.lblCrossWidthArms = QLabel(self.groupBox_2)
        self.lblCrossWidthArms.setObjectName(u"lblCrossWidthArms")
        self.lblCrossWidthArms.setGeometry(QRect(10, 80, 120, 40))
        self.lblCrossWidthArms.setMinimumSize(QSize(120, 40))
        self.lblCrossLengthArms = QLabel(self.groupBox_2)
        self.lblCrossLengthArms.setObjectName(u"lblCrossLengthArms")
        self.lblCrossLengthArms.setGeometry(QRect(10, 30, 120, 40))
        self.lblCrossLengthArms.setMinimumSize(QSize(120, 40))
        self.dsbCrossLegthArms = QDoubleSpinBox(self.groupBox_2)
        self.dsbCrossLegthArms.setObjectName(u"dsbCrossLegthArms")
        self.dsbCrossLegthArms.setGeometry(QRect(160, 30, 80, 40))
        self.dsbCrossLegthArms.setMinimumSize(QSize(80, 40))
        self.dsbCrossWidthArms = QDoubleSpinBox(self.groupBox_2)
        self.dsbCrossWidthArms.setObjectName(u"dsbCrossWidthArms")
        self.dsbCrossWidthArms.setGeometry(QRect(160, 80, 80, 40))
        self.dsbCrossWidthArms.setMinimumSize(QSize(80, 40))
        self.stackedWidget.addWidget(self.pageCross)
        self.pageMorris = QWidget()
        self.pageMorris.setObjectName(u"pageMorris")
        self.groupBox_3 = QGroupBox(self.pageMorris)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 10, 271, 468))
        self.groupBox_3.setMinimumSize(QSize(270, 468))
        self.tabWidget = QTabWidget(self.groupBox_3)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 20, 251, 440))
        self.tabWidget.setMinimumSize(QSize(250, 440))
        self.part1 = QWidget()
        self.part1.setObjectName(u"part1")
        self.scrollArea = QScrollArea(self.part1)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(10, 10, 231, 271))
        self.scrollArea.setMinimumSize(QSize(230, 270))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 229, 269))
        self.scrollAreaWidgetContents_2.setMinimumSize(QSize(200, 250))
        self.layoutWidget = QWidget(self.scrollAreaWidgetContents_2)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 10, 211, 251))
        self.formLayout = QFormLayout(self.layoutWidget)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.lblBaseField = QLabel(self.layoutWidget)
        self.lblBaseField.setObjectName(u"lblBaseField")

        self.formLayout.setWidget(0, QFormLayout.ItemRole.LabelRole, self.lblBaseField)

        self.lbSpace = QLabel(self.layoutWidget)
        self.lbSpace.setObjectName(u"lbSpace")

        self.formLayout.setWidget(1, QFormLayout.ItemRole.LabelRole, self.lbSpace)

        self.sbSpace = QSpinBox(self.layoutWidget)
        self.sbSpace.setObjectName(u"sbSpace")

        self.formLayout.setWidget(1, QFormLayout.ItemRole.FieldRole, self.sbSpace)

        self.lblPlatform = QLabel(self.layoutWidget)
        self.lblPlatform.setObjectName(u"lblPlatform")

        self.formLayout.setWidget(2, QFormLayout.ItemRole.LabelRole, self.lblPlatform)

        self.sbPlatform = QSpinBox(self.layoutWidget)
        self.sbPlatform.setObjectName(u"sbPlatform")

        self.formLayout.setWidget(2, QFormLayout.ItemRole.FieldRole, self.sbPlatform)

        self.lblBaseField_2 = QLabel(self.layoutWidget)
        self.lblBaseField_2.setObjectName(u"lblBaseField_2")

        self.formLayout.setWidget(3, QFormLayout.ItemRole.LabelRole, self.lblBaseField_2)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.layoutWidget1 = QWidget(self.part1)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(10, 290, 231, 104))
        self.gridLayout_6 = QGridLayout(self.layoutWidget1)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.btnAdd = QPushButton(self.layoutWidget1)
        self.btnAdd.setObjectName(u"btnAdd")
        self.btnAdd.setMinimumSize(QSize(210, 30))

        self.gridLayout_6.addWidget(self.btnAdd, 0, 0, 1, 1)

        self.btnRemove = QPushButton(self.layoutWidget1)
        self.btnRemove.setObjectName(u"btnRemove")
        self.btnRemove.setMinimumSize(QSize(210, 30))

        self.gridLayout_6.addWidget(self.btnRemove, 1, 0, 1, 1)

        self.btnReset = QPushButton(self.layoutWidget1)
        self.btnReset.setObjectName(u"btnReset")
        self.btnReset.setMinimumSize(QSize(210, 30))

        self.gridLayout_6.addWidget(self.btnReset, 2, 0, 1, 1)

        self.tabWidget.addTab(self.part1, "")
        self.part2 = QWidget()
        self.part2.setObjectName(u"part2")
        self.cbMarkup = QComboBox(self.part2)
        self.cbMarkup.addItem("")
        self.cbMarkup.addItem("")
        self.cbMarkup.setObjectName(u"cbMarkup")
        self.cbMarkup.setGeometry(QRect(10, 60, 221, 41))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(200)
        sizePolicy1.setVerticalStretch(40)
        sizePolicy1.setHeightForWidth(self.cbMarkup.sizePolicy().hasHeightForWidth())
        self.cbMarkup.setSizePolicy(sizePolicy1)
        self.cbMarkup.setMinimumSize(QSize(200, 40))
        self.lblMarkup = QLabel(self.part2)
        self.lblMarkup.setObjectName(u"lblMarkup")
        self.lblMarkup.setGeometry(QRect(10, 10, 131, 41))
        self.lblMarkup.setMinimumSize(QSize(130, 40))
        self.sbDiam = QSpinBox(self.part2)
        self.sbDiam.setObjectName(u"sbDiam")
        self.sbDiam.setGeometry(QRect(175, 160, 61, 41))
        self.sbDiam.setMinimumSize(QSize(60, 40))
        self.lblDiam = QLabel(self.part2)
        self.lblDiam.setObjectName(u"lblDiam")
        self.lblDiam.setGeometry(QRect(10, 160, 161, 41))
        self.lblDiam.setMinimumSize(QSize(130, 40))
        self.lblAngle = QLabel(self.part2)
        self.lblAngle.setObjectName(u"lblAngle")
        self.lblAngle.setGeometry(QRect(10, 110, 131, 41))
        self.lblAngle.setMinimumSize(QSize(130, 40))
        self.sbAngle = QSpinBox(self.part2)
        self.sbAngle.setObjectName(u"sbAngle")
        self.sbAngle.setGeometry(QRect(175, 110, 61, 41))
        self.sbAngle.setMinimumSize(QSize(60, 40))
        self.tabWidget.addTab(self.part2, "")
        self.stackedWidget.addWidget(self.pageMorris)
        self.pageLDT = QWidget()
        self.pageLDT.setObjectName(u"pageLDT")
        self.groupBox_8 = QGroupBox(self.pageLDT)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(10, 10, 261, 371))
        self.cbHasDarkRoom = QCheckBox(self.groupBox_8)
        self.cbHasDarkRoom.setObjectName(u"cbHasDarkRoom")
        self.cbHasDarkRoom.setGeometry(QRect(10, 220, 240, 40))
        self.cbHasDarkRoom.setMinimumSize(QSize(80, 40))
        self.lblLDTradius = QLabel(self.groupBox_8)
        self.lblLDTradius.setObjectName(u"lblLDTradius")
        self.lblLDTradius.setGeometry(QRect(10, 120, 161, 40))
        self.lblLDTradius.setMinimumSize(QSize(150, 40))
        self.lblLDTSizePass = QLabel(self.groupBox_8)
        self.lblLDTSizePass.setObjectName(u"lblLDTSizePass")
        self.lblLDTSizePass.setGeometry(QRect(10, 170, 150, 40))
        self.lblLDTSizePass.setMinimumSize(QSize(150, 40))
        self.lblLDTWidthArmsLight = QLabel(self.groupBox_8)
        self.lblLDTWidthArmsLight.setObjectName(u"lblLDTWidthArmsLight")
        self.lblLDTWidthArmsLight.setGeometry(QRect(10, 70, 161, 40))
        self.lblLDTWidthArmsLight.setMinimumSize(QSize(120, 40))
        self.lblLDTLengthArmsLight = QLabel(self.groupBox_8)
        self.lblLDTLengthArmsLight.setObjectName(u"lblLDTLengthArmsLight")
        self.lblLDTLengthArmsLight.setGeometry(QRect(10, 20, 161, 40))
        self.lblLDTLengthArmsLight.setMinimumSize(QSize(120, 40))
        self.dsbLDTLegthArmsLight = QDoubleSpinBox(self.groupBox_8)
        self.dsbLDTLegthArmsLight.setObjectName(u"dsbLDTLegthArmsLight")
        self.dsbLDTLegthArmsLight.setGeometry(QRect(175, 20, 75, 40))
        self.dsbLDTLegthArmsLight.setMinimumSize(QSize(75, 40))
        self.dsbLDTWidthArmsLight = QDoubleSpinBox(self.groupBox_8)
        self.dsbLDTWidthArmsLight.setObjectName(u"dsbLDTWidthArmsLight")
        self.dsbLDTWidthArmsLight.setGeometry(QRect(175, 70, 75, 40))
        self.dsbLDTWidthArmsLight.setMinimumSize(QSize(75, 40))
        self.lblLDTLengthArmsDark = QLabel(self.groupBox_8)
        self.lblLDTLengthArmsDark.setObjectName(u"lblLDTLengthArmsDark")
        self.lblLDTLengthArmsDark.setGeometry(QRect(10, 260, 161, 40))
        self.lblLDTLengthArmsDark.setMinimumSize(QSize(120, 40))
        self.lblLDTWidthArmsDark = QLabel(self.groupBox_8)
        self.lblLDTWidthArmsDark.setObjectName(u"lblLDTWidthArmsDark")
        self.lblLDTWidthArmsDark.setGeometry(QRect(10, 310, 161, 40))
        self.lblLDTWidthArmsDark.setMinimumSize(QSize(120, 40))
        self.dsbLDTLegthArmsDark = QDoubleSpinBox(self.groupBox_8)
        self.dsbLDTLegthArmsDark.setObjectName(u"dsbLDTLegthArmsDark")
        self.dsbLDTLegthArmsDark.setGeometry(QRect(175, 260, 75, 40))
        self.dsbLDTLegthArmsDark.setMinimumSize(QSize(75, 40))
        self.dsbLDTWidthArmsDark = QDoubleSpinBox(self.groupBox_8)
        self.dsbLDTWidthArmsDark.setObjectName(u"dsbLDTWidthArmsDark")
        self.dsbLDTWidthArmsDark.setGeometry(QRect(175, 310, 75, 40))
        self.dsbLDTWidthArmsDark.setMinimumSize(QSize(75, 40))
        self.dsbLDTradius = QDoubleSpinBox(self.groupBox_8)
        self.dsbLDTradius.setObjectName(u"dsbLDTradius")
        self.dsbLDTradius.setGeometry(QRect(175, 120, 75, 40))
        self.dsbLDTradius.setMinimumSize(QSize(75, 40))
        self.dsbLDTSizePass = QDoubleSpinBox(self.groupBox_8)
        self.dsbLDTSizePass.setObjectName(u"dsbLDTSizePass")
        self.dsbLDTSizePass.setGeometry(QRect(175, 170, 75, 40))
        self.dsbLDTSizePass.setMinimumSize(QSize(75, 40))
        self.stackedWidget.addWidget(self.pageLDT)
        self.pageYmt = QWidget()
        self.pageYmt.setObjectName(u"pageYmt")
        self.groupBox_5 = QGroupBox(self.pageYmt)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 10, 261, 471))
        self.tabWidget_2 = QTabWidget(self.groupBox_5)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(10, 20, 241, 311))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.dsbWidthArms = QDoubleSpinBox(self.tab)
        self.dsbWidthArms.setObjectName(u"dsbWidthArms")
        self.dsbWidthArms.setGeometry(QRect(150, 70, 80, 40))
        self.dsbWidthArms.setMinimumSize(QSize(80, 40))
        self.lblLengthArms = QLabel(self.tab)
        self.lblLengthArms.setObjectName(u"lblLengthArms")
        self.lblLengthArms.setGeometry(QRect(5, 20, 120, 40))
        self.lblLengthArms.setMinimumSize(QSize(120, 40))
        self.dsbLegthArms = QDoubleSpinBox(self.tab)
        self.dsbLegthArms.setObjectName(u"dsbLegthArms")
        self.dsbLegthArms.setGeometry(QRect(150, 20, 80, 40))
        self.dsbLegthArms.setMinimumSize(QSize(80, 40))
        self.lblWidthArms = QLabel(self.tab)
        self.lblWidthArms.setObjectName(u"lblWidthArms")
        self.lblWidthArms.setGeometry(QRect(5, 70, 120, 40))
        self.lblWidthArms.setMinimumSize(QSize(120, 40))
        self.sblCountObject = QSpinBox(self.tab)
        self.sblCountObject.setObjectName(u"sblCountObject")
        self.sblCountObject.setGeometry(QRect(150, 170, 80, 40))
        self.sblCountObject.setMinimumSize(QSize(80, 40))
        self.sbAngleArms = QSpinBox(self.tab)
        self.sbAngleArms.setObjectName(u"sbAngleArms")
        self.sbAngleArms.setGeometry(QRect(150, 120, 80, 40))
        self.sbAngleArms.setMinimumSize(QSize(80, 40))
        self.lblAngleArms = QLabel(self.tab)
        self.lblAngleArms.setObjectName(u"lblAngleArms")
        self.lblAngleArms.setGeometry(QRect(5, 120, 120, 40))
        self.lblAngleArms.setMinimumSize(QSize(120, 40))
        self.lblCountObject = QLabel(self.tab)
        self.lblCountObject.setObjectName(u"lblCountObject")
        self.lblCountObject.setGeometry(QRect(5, 170, 131, 40))
        self.lblCountObject.setMinimumSize(QSize(120, 40))
        self.lblAreaInt = QLabel(self.tab)
        self.lblAreaInt.setObjectName(u"lblAreaInt")
        self.lblAreaInt.setGeometry(QRect(5, 220, 141, 40))
        self.lblAreaInt.setMinimumSize(QSize(120, 40))
        self.sblAreaInt = QSpinBox(self.tab)
        self.sblAreaInt.setObjectName(u"sblAreaInt")
        self.sblAreaInt.setGeometry(QRect(150, 220, 80, 40))
        self.sblAreaInt.setMinimumSize(QSize(80, 40))
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.sbYMTalpha3 = QSpinBox(self.tab_2)
        self.sbYMTalpha3.setObjectName(u"sbYMTalpha3")
        self.sbYMTalpha3.setGeometry(QRect(150, 170, 80, 40))
        self.sbYMTalpha3.setMinimumSize(QSize(80, 40))
        self.btnResetAngle = QPushButton(self.tab_2)
        self.btnResetAngle.setObjectName(u"btnResetAngle")
        self.btnResetAngle.setGeometry(QRect(30, 220, 180, 40))
        self.btnResetAngle.setMinimumSize(QSize(80, 40))
        self.lblYMTalpha1 = QLabel(self.tab_2)
        self.lblYMTalpha1.setObjectName(u"lblYMTalpha1")
        self.lblYMTalpha1.setGeometry(QRect(5, 70, 120, 40))
        self.lblYMTalpha1.setMinimumSize(QSize(120, 40))
        self.lblYMTalpha3 = QLabel(self.tab_2)
        self.lblYMTalpha3.setObjectName(u"lblYMTalpha3")
        self.lblYMTalpha3.setGeometry(QRect(5, 170, 151, 40))
        self.lblYMTalpha3.setMinimumSize(QSize(120, 40))
        self.lblYMTalpha2 = QLabel(self.tab_2)
        self.lblYMTalpha2.setObjectName(u"lblYMTalpha2")
        self.lblYMTalpha2.setGeometry(QRect(5, 120, 151, 40))
        self.lblYMTalpha2.setMinimumSize(QSize(120, 40))
        self.sbYMTalpha1 = QSpinBox(self.tab_2)
        self.sbYMTalpha1.setObjectName(u"sbYMTalpha1")
        self.sbYMTalpha1.setGeometry(QRect(150, 70, 80, 40))
        self.sbYMTalpha1.setMinimumSize(QSize(80, 40))
        self.sbYMTalpha2 = QSpinBox(self.tab_2)
        self.sbYMTalpha2.setObjectName(u"sbYMTalpha2")
        self.sbYMTalpha2.setGeometry(QRect(150, 120, 80, 40))
        self.sbYMTalpha2.setMinimumSize(QSize(80, 40))
        self.lblYMTsumAngle = QLabel(self.tab_2)
        self.lblYMTsumAngle.setObjectName(u"lblYMTsumAngle")
        self.lblYMTsumAngle.setGeometry(QRect(5, 20, 221, 41))
        self.lblYMTsumAngle.setMinimumSize(QSize(200, 40))
        self.tabWidget_2.addTab(self.tab_2, "")
        self.stackedWidget.addWidget(self.pageYmt)
        self.pageTCS = QWidget()
        self.pageTCS.setObjectName(u"pageTCS")
        self.groupBox_6 = QGroupBox(self.pageTCS)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(10, 10, 261, 381))
        self.lblTCSwidth = QLabel(self.groupBox_6)
        self.lblTCSwidth.setObjectName(u"lblTCSwidth")
        self.lblTCSwidth.setGeometry(QRect(5, 30, 151, 40))
        self.lblTCSwidth.setMinimumSize(QSize(80, 40))
        self.dsbTCSwidth = QDoubleSpinBox(self.groupBox_6)
        self.dsbTCSwidth.setObjectName(u"dsbTCSwidth")
        self.dsbTCSwidth.setGeometry(QRect(175, 30, 80, 40))
        self.dsbTCSwidth.setMinimumSize(QSize(80, 40))
        self.dsbTCSlenght = QDoubleSpinBox(self.groupBox_6)
        self.dsbTCSlenght.setObjectName(u"dsbTCSlenght")
        self.dsbTCSlenght.setGeometry(QRect(175, 80, 80, 40))
        self.dsbTCSlenght.setMinimumSize(QSize(80, 40))
        self.lblTCSlength = QLabel(self.groupBox_6)
        self.lblTCSlength.setObjectName(u"lblTCSlength")
        self.lblTCSlength.setGeometry(QRect(5, 80, 151, 40))
        self.lblTCSlength.setMinimumSize(QSize(80, 40))
        self.dsbTCSleftlegth = QDoubleSpinBox(self.groupBox_6)
        self.dsbTCSleftlegth.setObjectName(u"dsbTCSleftlegth")
        self.dsbTCSleftlegth.setGeometry(QRect(175, 130, 80, 40))
        self.dsbTCSleftlegth.setMinimumSize(QSize(80, 40))
        self.lblTCSleftlegth = QLabel(self.groupBox_6)
        self.lblTCSleftlegth.setObjectName(u"lblTCSleftlegth")
        self.lblTCSleftlegth.setGeometry(QRect(5, 130, 151, 40))
        self.lblTCSleftlegth.setMinimumSize(QSize(80, 40))
        self.dsbTCSrightlegth = QDoubleSpinBox(self.groupBox_6)
        self.dsbTCSrightlegth.setObjectName(u"dsbTCSrightlegth")
        self.dsbTCSrightlegth.setGeometry(QRect(175, 180, 80, 40))
        self.dsbTCSrightlegth.setMinimumSize(QSize(80, 40))
        self.lblTCSrightlegth = QLabel(self.groupBox_6)
        self.lblTCSrightlegth.setObjectName(u"lblTCSrightlegth")
        self.lblTCSrightlegth.setGeometry(QRect(5, 180, 171, 40))
        self.lblTCSrightlegth.setMinimumSize(QSize(80, 40))
        self.lblTCSAreaInt = QLabel(self.groupBox_6)
        self.lblTCSAreaInt.setObjectName(u"lblTCSAreaInt")
        self.lblTCSAreaInt.setGeometry(QRect(5, 280, 161, 40))
        self.lblTCSAreaInt.setMinimumSize(QSize(120, 40))
        self.lblTCSCountObject = QLabel(self.groupBox_6)
        self.lblTCSCountObject.setObjectName(u"lblTCSCountObject")
        self.lblTCSCountObject.setGeometry(QRect(5, 230, 151, 40))
        self.lblTCSCountObject.setMinimumSize(QSize(120, 40))
        self.sbTCSCountObject = QSpinBox(self.groupBox_6)
        self.sbTCSCountObject.setObjectName(u"sbTCSCountObject")
        self.sbTCSCountObject.setGeometry(QRect(175, 230, 80, 40))
        self.sbTCSCountObject.setMinimumSize(QSize(80, 40))
        self.sbTCSAreaInt = QSpinBox(self.groupBox_6)
        self.sbTCSAreaInt.setObjectName(u"sbTCSAreaInt")
        self.sbTCSAreaInt.setGeometry(QRect(175, 280, 80, 40))
        self.sbTCSAreaInt.setMinimumSize(QSize(80, 40))
        self.lblTCSSizePass = QLabel(self.groupBox_6)
        self.lblTCSSizePass.setObjectName(u"lblTCSSizePass")
        self.lblTCSSizePass.setGeometry(QRect(5, 330, 150, 40))
        self.lblTCSSizePass.setMinimumSize(QSize(150, 40))
        self.sbTCSSizePass = QSpinBox(self.groupBox_6)
        self.sbTCSSizePass.setObjectName(u"sbTCSSizePass")
        self.sbTCSSizePass.setGeometry(QRect(175, 330, 80, 40))
        self.sbTCSSizePass.setMinimumSize(QSize(80, 40))
        self.stackedWidget.addWidget(self.pageTCS)
        self.lblInfo = QLabel(settings)
        self.lblInfo.setObjectName(u"lblInfo")
        self.lblInfo.setGeometry(QRect(311, 201, 16, 16))
        self.layoutWidget2 = QWidget(settings)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(580, 497, 471, 62))
        self.gridLayout_4 = QGridLayout(self.layoutWidget2)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.btnAccept = QPushButton(self.layoutWidget2)
        self.btnAccept.setObjectName(u"btnAccept")
        self.btnAccept.setMinimumSize(QSize(170, 60))
        self.btnAccept.setStyleSheet(u"")

        self.gridLayout_4.addWidget(self.btnAccept, 0, 0, 1, 1)

        self.btnReject = QPushButton(self.layoutWidget2)
        self.btnReject.setObjectName(u"btnReject")
        self.btnReject.setMinimumSize(QSize(170, 60))
        self.btnReject.setStyleSheet(u"")

        self.gridLayout_4.addWidget(self.btnReject, 0, 2, 1, 1)

        self.horizontalSpacer_2 = QSpacerItem(36, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_4.addItem(self.horizontalSpacer_2, 0, 1, 1, 1)

        self.groupBox_4 = QGroupBox(settings)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(570, 20, 201, 241))
        self.btnScale = QPushButton(self.groupBox_4)
        self.btnScale.setObjectName(u"btnScale")
        self.btnScale.setGeometry(QRect(10, 30, 180, 40))
        self.btnScale.setMinimumSize(QSize(80, 40))
        self.lblTypeField = QLabel(self.groupBox_4)
        self.lblTypeField.setObjectName(u"lblTypeField")
        self.lblTypeField.setGeometry(QRect(11, 80, 80, 40))
        self.lblTypeField.setMinimumSize(QSize(80, 40))
        self.lblSize = QLabel(self.groupBox_4)
        self.lblSize.setObjectName(u"lblSize")
        self.lblSize.setGeometry(QRect(11, 130, 91, 40))
        self.lblSize.setMinimumSize(QSize(80, 40))
        self.lblModel = QLabel(self.groupBox_4)
        self.lblModel.setObjectName(u"lblModel")
        self.lblModel.setGeometry(QRect(11, 180, 80, 40))
        self.lblModel.setMinimumSize(QSize(80, 40))
        self.cbModel = QComboBox(self.groupBox_4)
        self.cbModel.addItem("")
        self.cbModel.addItem("")
        self.cbModel.addItem("")
        self.cbModel.addItem("")
        self.cbModel.addItem("")
        self.cbModel.addItem("")
        self.cbModel.addItem("")
        self.cbModel.setObjectName(u"cbModel")
        self.cbModel.setGeometry(QRect(100, 180, 93, 40))
        self.cbModel.setMinimumSize(QSize(70, 40))
        self.spinbSize = QSpinBox(self.groupBox_4)
        self.spinbSize.setObjectName(u"spinbSize")
        self.spinbSize.setGeometry(QRect(100, 130, 91, 40))
        self.spinbSize.setMinimumSize(QSize(70, 40))
        self.cbFieldType = QComboBox(self.groupBox_4)
        self.cbFieldType.addItem("")
        self.cbFieldType.addItem("")
        self.cbFieldType.addItem("")
        self.cbFieldType.addItem("")
        self.cbFieldType.addItem("")
        self.cbFieldType.addItem("")
        self.cbFieldType.addItem("")
        self.cbFieldType.setObjectName(u"cbFieldType")
        self.cbFieldType.setGeometry(QRect(100, 80, 91, 40))
        self.cbFieldType.setMinimumSize(QSize(70, 40))
        self.btnUp = QPushButton(settings)
        self.btnUp.setObjectName(u"btnUp")
        self.btnUp.setGeometry(QRect(630, 340, 75, 24))
        self.btnDown = QPushButton(settings)
        self.btnDown.setObjectName(u"btnDown")
        self.btnDown.setGeometry(QRect(630, 420, 75, 24))
        self.btnRight = QPushButton(settings)
        self.btnRight.setObjectName(u"btnRight")
        self.btnRight.setGeometry(QRect(690, 380, 75, 24))
        self.btnLeft = QPushButton(settings)
        self.btnLeft.setObjectName(u"btnLeft")
        self.btnLeft.setGeometry(QRect(570, 380, 75, 24))
        self.cbPoints = QComboBox(settings)
        self.cbPoints.setObjectName(u"cbPoints")
        self.cbPoints.setGeometry(QRect(570, 280, 201, 40))
        self.cbPoints.setMinimumSize(QSize(70, 40))
        self.groupBox_4.raise_()
        self.lblImage.raise_()
        self.stackedWidget.raise_()
        self.lblInfo.raise_()
        self.layoutWidget2.raise_()
        self.btnUp.raise_()
        self.btnDown.raise_()
        self.btnRight.raise_()
        self.btnLeft.raise_()
        self.cbPoints.raise_()

        self.retranslateUi(settings)

        self.stackedWidget.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(settings)
    # setupUi

    def retranslateUi(self, settings):
        settings.setWindowTitle(QCoreApplication.translate("settings", u"Video marking", None))
        self.lblImage.setText("")
        self.groupBox.setTitle(QCoreApplication.translate("settings", u"Field parameters", None))
        self.lblSmallField.setText(QCoreApplication.translate("settings", u"Smaller field", None))
        self.lblMediumField.setText(QCoreApplication.translate("settings", u"Middle field", None))
        self.lblLargeField.setText(QCoreApplication.translate("settings", u"Large field", None))
        self.lblBOXAreaInt.setText(QCoreApplication.translate("settings", u"Size of area of interest", None))
        self.lblBOXCountObject.setText(QCoreApplication.translate("settings", u"Number of objects", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("settings", u"Field parameters", None))
        self.lblText.setText(QCoreApplication.translate("settings", u"Open fields:", None))
        self.checkbCenter.setText(QCoreApplication.translate("settings", u"center", None))
        self.checkbUp.setText(QCoreApplication.translate("settings", u"up", None))
        self.checkbLeft.setText(QCoreApplication.translate("settings", u"left", None))
        self.checkbRight.setText(QCoreApplication.translate("settings", u"right", None))
        self.checkbDown.setText(QCoreApplication.translate("settings", u"down", None))
        self.lblCrossWidthArms.setText(QCoreApplication.translate("settings", u"Sleeve width, cm", None))
        self.lblCrossLengthArms.setText(QCoreApplication.translate("settings", u"Sleeve length, cm", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("settings", u"Field parameters", None))
        self.lblBaseField.setText(QCoreApplication.translate("settings", u"Basic fields:", None))
        self.lbSpace.setText(QCoreApplication.translate("settings", u"Main field", None))
        self.lblPlatform.setText(QCoreApplication.translate("settings", u"Platform", None))
        self.lblBaseField_2.setText(QCoreApplication.translate("settings", u"Additional fields:", None))
        self.btnAdd.setText(QCoreApplication.translate("settings", u"Add field", None))
        self.btnRemove.setText(QCoreApplication.translate("settings", u"Delete last", None))
        self.btnReset.setText(QCoreApplication.translate("settings", u"Reset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.part1), QCoreApplication.translate("settings", u"Tab 1", None))
        self.cbMarkup.setItemText(0, QCoreApplication.translate("settings", u"to 4 quadrants", None))
        self.cbMarkup.setItemText(1, QCoreApplication.translate("settings", u"to 8 quadrants", None))

        self.lblMarkup.setText(QCoreApplication.translate("settings", u"Selecting markup:", None))
        self.lblDiam.setText(QCoreApplication.translate("settings", u"Diameter of the second circle", None))
        self.lblAngle.setText(QCoreApplication.translate("settings", u"Angle of rotation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.part2), QCoreApplication.translate("settings", u"Tab 2", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("settings", u"Field parameters", None))
        self.cbHasDarkRoom.setText(QCoreApplication.translate("settings", u"Presence of a dark area", None))
        self.lblLDTradius.setText(QCoreApplication.translate("settings", u"Radius of area of interest, cm", None))
        self.lblLDTSizePass.setText(QCoreApplication.translate("settings", u"Passage size, cm", None))
        self.lblLDTWidthArmsLight.setText(QCoreApplication.translate("settings", u"Sleeve width (light), cm", None))
        self.lblLDTLengthArmsLight.setText(QCoreApplication.translate("settings", u"Sleeve length (light), cm", None))
        self.lblLDTLengthArmsDark.setText(QCoreApplication.translate("settings", u"Sleeve length (dark), cm", None))
        self.lblLDTWidthArmsDark.setText(QCoreApplication.translate("settings", u"Sleeve width (dark), cm", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("settings", u"Field parameters", None))
        self.lblLengthArms.setText(QCoreApplication.translate("settings", u"Sleeve length, cm", None))
        self.lblWidthArms.setText(QCoreApplication.translate("settings", u"Sleeve width, cm", None))
        self.lblAngleArms.setText(QCoreApplication.translate("settings", u"Angle of rotation", None))
        self.lblCountObject.setText(QCoreApplication.translate("settings", u"Number of objects", None))
        self.lblAreaInt.setText(QCoreApplication.translate("settings", u"Size of area of interest", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), QCoreApplication.translate("settings", u"Tab 1", None))
        self.btnResetAngle.setText(QCoreApplication.translate("settings", u"\u0421\u0431\u0440\u043e\u0441\u0438\u0442\u044c (\u043f\u043e 120\u00b0)", None))
        self.lblYMTalpha1.setText(QCoreApplication.translate("settings", u"\u0423\u0433\u043e\u043b 1, \u00b0", None))
        self.lblYMTalpha3.setText(QCoreApplication.translate("settings", u"\u0423\u0433\u043e\u043b 3, \u00b0", None))
        self.lblYMTalpha2.setText(QCoreApplication.translate("settings", u"\u0423\u0433\u043e\u043b 2, \u00b0", None))
        self.lblYMTsumAngle.setText("")
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), QCoreApplication.translate("settings", u"Tab 2", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("settings", u"Field parameters", None))
        self.lblTCSwidth.setText(QCoreApplication.translate("settings", u"Total field width, cm", None))
        self.lblTCSlength.setText(QCoreApplication.translate("settings", u"Total length of the field, cm", None))
        self.lblTCSleftlegth.setText(QCoreApplication.translate("settings", u"Length of left section, cm", None))
        self.lblTCSrightlegth.setText(QCoreApplication.translate("settings", u"Length of the right section, cm", None))
        self.lblTCSAreaInt.setText(QCoreApplication.translate("settings", u"Size of area of interest", None))
        self.lblTCSCountObject.setText(QCoreApplication.translate("settings", u"Number of objects", None))
        self.lblTCSSizePass.setText(QCoreApplication.translate("settings", u"Passage size, cm", None))
        self.lblInfo.setText("")
        self.btnAccept.setText(QCoreApplication.translate("settings", u"Confirm", None))
        self.btnReject.setText(QCoreApplication.translate("settings", u"Cancel", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("settings", u"Basic parameters", None))
        self.btnScale.setText(QCoreApplication.translate("settings", u"Set distance", None))
        self.lblTypeField.setText(QCoreApplication.translate("settings", u"Field type", None))
        self.lblSize.setText(QCoreApplication.translate("settings", u"Distance, cm", None))
        self.lblModel.setText(QCoreApplication.translate("settings", u"Model", None))
        self.cbModel.setItemText(0, QCoreApplication.translate("settings", u"auto", None))
        self.cbModel.setItemText(1, QCoreApplication.translate("settings", u"op_pkl", None))
        self.cbModel.setItemText(2, QCoreApplication.translate("settings", u"morris_black", None))
        self.cbModel.setItemText(3, QCoreApplication.translate("settings", u"morris_white", None))
        self.cbModel.setItemText(4, QCoreApplication.translate("settings", u"ldt", None))
        self.cbModel.setItemText(5, QCoreApplication.translate("settings", u"ymt", None))
        self.cbModel.setItemText(6, QCoreApplication.translate("settings", u"tcs", None))

        self.cbFieldType.setItemText(0, QCoreApplication.translate("settings", u"None", None))
        self.cbFieldType.setItemText(1, QCoreApplication.translate("settings", u"box", None))
        self.cbFieldType.setItemText(2, QCoreApplication.translate("settings", u"cross", None))
        self.cbFieldType.setItemText(3, QCoreApplication.translate("settings", u"morris", None))
        self.cbFieldType.setItemText(4, QCoreApplication.translate("settings", u"ldt", None))
        self.cbFieldType.setItemText(5, QCoreApplication.translate("settings", u"ymt", None))
        self.cbFieldType.setItemText(6, QCoreApplication.translate("settings", u"tcs", None))

        self.btnUp.setText(QCoreApplication.translate("settings", u"Up", None))
        self.btnDown.setText(QCoreApplication.translate("settings", u"Down", None))
        self.btnRight.setText(QCoreApplication.translate("settings", u"Right", None))
        self.btnLeft.setText(QCoreApplication.translate("settings", u"Left", None))
    # retranslateUi

