# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'widget_graphs.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDoubleSpinBox, QGridLayout,
    QGroupBox, QLabel, QPushButton, QSizePolicy,
    QSpinBox, QWidget)

class Ui_widgetGraphs(object):
    def setupUi(self, widgetGraphs):
        if not widgetGraphs.objectName():
            widgetGraphs.setObjectName(u"widgetGraphs")
        widgetGraphs.resize(1110, 810)
        widgetGraphs.setMinimumSize(QSize(1110, 810))
        self.gridLayout = QGridLayout(widgetGraphs)
        self.gridLayout.setObjectName(u"gridLayout")
        self.btnBuildGraph = QPushButton(widgetGraphs)
        self.btnBuildGraph.setObjectName(u"btnBuildGraph")
        self.btnBuildGraph.setMinimumSize(QSize(180, 40))

        self.gridLayout.addWidget(self.btnBuildGraph, 1, 0, 1, 1)

        self.btnLoadData = QPushButton(widgetGraphs)
        self.btnLoadData.setObjectName(u"btnLoadData")
        self.btnLoadData.setMinimumSize(QSize(180, 40))

        self.gridLayout.addWidget(self.btnLoadData, 1, 1, 1, 1)

        self.lblTrajectory = QLabel(widgetGraphs)
        self.lblTrajectory.setObjectName(u"lblTrajectory")
        self.lblTrajectory.setMinimumSize(QSize(746, 746))
        self.lblTrajectory.setStyleSheet(u"background: black")

        self.gridLayout.addWidget(self.lblTrajectory, 0, 0, 1, 3)

        self.btnExportDataAll = QPushButton(widgetGraphs)
        self.btnExportDataAll.setObjectName(u"btnExportDataAll")
        self.btnExportDataAll.setMinimumSize(QSize(180, 40))

        self.gridLayout.addWidget(self.btnExportDataAll, 1, 4, 1, 1)

        self.btnSaveGraph = QPushButton(widgetGraphs)
        self.btnSaveGraph.setObjectName(u"btnSaveGraph")
        self.btnSaveGraph.setMinimumSize(QSize(180, 40))

        self.gridLayout.addWidget(self.btnSaveGraph, 1, 2, 1, 1)

        self.groupBox = QGroupBox(widgetGraphs)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setMinimumSize(QSize(320, 700))
        self.chbShStEn = QCheckBox(self.groupBox)
        self.chbShStEn.setObjectName(u"chbShStEn")
        self.chbShStEn.setGeometry(QRect(10, 25, 280, 30))
        self.chbShStEn.setMinimumSize(QSize(280, 30))
        self.checkbDiveTraj = QCheckBox(self.groupBox)
        self.checkbDiveTraj.setObjectName(u"checkbDiveTraj")
        self.checkbDiveTraj.setGeometry(QRect(10, 50, 280, 30))
        self.checkbDiveTraj.setMinimumSize(QSize(280, 30))
        self.dsbSpdThFS = QDoubleSpinBox(self.groupBox)
        self.dsbSpdThFS.setObjectName(u"dsbSpdThFS")
        self.dsbSpdThFS.setGeometry(QRect(240, 180, 70, 30))
        self.dsbSpdThFS.setMinimumSize(QSize(70, 30))
        self.chbAddZones = QCheckBox(self.groupBox)
        self.chbAddZones.setObjectName(u"chbAddZones")
        self.chbAddZones.setGeometry(QRect(10, 75, 280, 30))
        self.chbAddZones.setMinimumSize(QSize(280, 30))
        self.dsbStopTimeTh = QDoubleSpinBox(self.groupBox)
        self.dsbStopTimeTh.setObjectName(u"dsbStopTimeTh")
        self.dsbStopTimeTh.setGeometry(QRect(240, 260, 70, 30))
        self.dsbStopTimeTh.setMinimumSize(QSize(70, 30))
        self.lblSpdThFS = QLabel(self.groupBox)
        self.lblSpdThFS.setObjectName(u"lblSpdThFS")
        self.lblSpdThFS.setGeometry(QRect(10, 180, 210, 30))
        self.lblSpdThFS.setMinimumSize(QSize(210, 30))
        self.dsbStopSpdTh = QDoubleSpinBox(self.groupBox)
        self.dsbStopSpdTh.setObjectName(u"dsbStopSpdTh")
        self.dsbStopSpdTh.setGeometry(QRect(240, 220, 70, 30))
        self.dsbStopSpdTh.setMinimumSize(QSize(70, 30))
        self.lblStopSpdTh = QLabel(self.groupBox)
        self.lblStopSpdTh.setObjectName(u"lblStopSpdTh")
        self.lblStopSpdTh.setGeometry(QRect(10, 220, 210, 30))
        self.lblStopSpdTh.setMinimumSize(QSize(210, 30))
        self.lblStopTimeTh = QLabel(self.groupBox)
        self.lblStopTimeTh.setObjectName(u"lblStopTimeTh")
        self.lblStopTimeTh.setGeometry(QRect(10, 260, 210, 30))
        self.lblStopTimeTh.setMinimumSize(QSize(210, 30))
        self.lblThick = QLabel(self.groupBox)
        self.lblThick.setObjectName(u"lblThick")
        self.lblThick.setGeometry(QRect(10, 404, 210, 30))
        self.lblThick.setMinimumSize(QSize(210, 30))
        self.chbBuildBr = QCheckBox(self.groupBox)
        self.chbBuildBr.setObjectName(u"chbBuildBr")
        self.chbBuildBr.setGeometry(QRect(180, 370, 130, 30))
        self.chbBuildBr.setMinimumSize(QSize(130, 30))
        self.sbThick = QSpinBox(self.groupBox)
        self.sbThick.setObjectName(u"sbThick")
        self.sbThick.setGeometry(QRect(240, 404, 70, 30))
        self.sbThick.setMinimumSize(QSize(70, 30))
        self.lblAngleDist = QLabel(self.groupBox)
        self.lblAngleDist.setObjectName(u"lblAngleDist")
        self.lblAngleDist.setGeometry(QRect(10, 440, 210, 30))
        self.lblAngleDist.setMinimumSize(QSize(210, 30))
        self.sbAngleDist = QSpinBox(self.groupBox)
        self.sbAngleDist.setObjectName(u"sbAngleDist")
        self.sbAngleDist.setGeometry(QRect(240, 440, 70, 30))
        self.sbAngleDist.setMinimumSize(QSize(70, 30))
        self.sbAngleTime = QSpinBox(self.groupBox)
        self.sbAngleTime.setObjectName(u"sbAngleTime")
        self.sbAngleTime.setGeometry(QRect(240, 476, 70, 30))
        self.sbAngleTime.setMinimumSize(QSize(70, 30))
        self.lblAngleTime = QLabel(self.groupBox)
        self.lblAngleTime.setObjectName(u"lblAngleTime")
        self.lblAngleTime.setGeometry(QRect(10, 476, 210, 30))
        self.lblAngleTime.setMinimumSize(QSize(210, 30))
        self.sbAnglePer = QSpinBox(self.groupBox)
        self.sbAnglePer.setObjectName(u"sbAnglePer")
        self.sbAnglePer.setGeometry(QRect(240, 512, 70, 30))
        self.sbAnglePer.setMinimumSize(QSize(70, 30))
        self.lblAnglePer = QLabel(self.groupBox)
        self.lblAnglePer.setObjectName(u"lblAnglePer")
        self.lblAnglePer.setGeometry(QRect(10, 512, 210, 30))
        self.lblAnglePer.setMinimumSize(QSize(210, 30))
        self.lblTimeStart = QLabel(self.groupBox)
        self.lblTimeStart.setObjectName(u"lblTimeStart")
        self.lblTimeStart.setGeometry(QRect(10, 548, 210, 30))
        self.lblTimeStart.setMinimumSize(QSize(210, 30))
        self.sbTimeStart = QSpinBox(self.groupBox)
        self.sbTimeStart.setObjectName(u"sbTimeStart")
        self.sbTimeStart.setGeometry(QRect(240, 548, 70, 30))
        self.sbTimeStart.setMinimumSize(QSize(70, 30))
        self.lblTimeEnd = QLabel(self.groupBox)
        self.lblTimeEnd.setObjectName(u"lblTimeEnd")
        self.lblTimeEnd.setGeometry(QRect(10, 584, 210, 30))
        self.lblTimeEnd.setMinimumSize(QSize(210, 30))
        self.sbTimeEnd = QSpinBox(self.groupBox)
        self.sbTimeEnd.setObjectName(u"sbTimeEnd")
        self.sbTimeEnd.setGeometry(QRect(240, 584, 70, 30))
        self.sbTimeEnd.setMinimumSize(QSize(70, 30))
        self.chbWrap = QCheckBox(self.groupBox)
        self.chbWrap.setObjectName(u"chbWrap")
        self.chbWrap.setGeometry(QRect(10, 370, 150, 30))
        self.chbWrap.setMinimumSize(QSize(150, 30))
        self.sbT0 = QSpinBox(self.groupBox)
        self.sbT0.setObjectName(u"sbT0")
        self.sbT0.setGeometry(QRect(10, 656, 70, 30))
        self.sbT0.setMinimumSize(QSize(70, 30))
        self.sbT1 = QSpinBox(self.groupBox)
        self.sbT1.setObjectName(u"sbT1")
        self.sbT1.setGeometry(QRect(87, 656, 70, 30))
        self.sbT1.setMinimumSize(QSize(70, 30))
        self.sbT2 = QSpinBox(self.groupBox)
        self.sbT2.setObjectName(u"sbT2")
        self.sbT2.setGeometry(QRect(164, 656, 70, 30))
        self.sbT2.setMinimumSize(QSize(70, 30))
        self.sbT3 = QSpinBox(self.groupBox)
        self.sbT3.setObjectName(u"sbT3")
        self.sbT3.setGeometry(QRect(240, 656, 70, 30))
        self.sbT3.setMinimumSize(QSize(70, 30))
        self.lblT0 = QLabel(self.groupBox)
        self.lblT0.setObjectName(u"lblT0")
        self.lblT0.setGeometry(QRect(10, 620, 50, 30))
        self.lblT0.setMinimumSize(QSize(50, 30))
        self.lblT1 = QLabel(self.groupBox)
        self.lblT1.setObjectName(u"lblT1")
        self.lblT1.setGeometry(QRect(90, 620, 50, 30))
        self.lblT1.setMinimumSize(QSize(50, 30))
        self.lblT2 = QLabel(self.groupBox)
        self.lblT2.setObjectName(u"lblT2")
        self.lblT2.setGeometry(QRect(170, 620, 50, 30))
        self.lblT2.setMinimumSize(QSize(50, 30))
        self.lblT3 = QLabel(self.groupBox)
        self.lblT3.setObjectName(u"lblT3")
        self.lblT3.setGeometry(QRect(240, 620, 5030, 30))
        self.lblT3.setMinimumSize(QSize(50, 30))
        self.lblThError = QLabel(self.groupBox)
        self.lblThError.setObjectName(u"lblThError")
        self.lblThError.setGeometry(QRect(10, 140, 210, 30))
        self.lblThError.setMinimumSize(QSize(210, 30))
        self.dsbThError = QDoubleSpinBox(self.groupBox)
        self.dsbThError.setObjectName(u"dsbThError")
        self.dsbThError.setGeometry(QRect(240, 140, 70, 30))
        self.dsbThError.setMinimumSize(QSize(70, 30))
        self.lblScale = QLabel(self.groupBox)
        self.lblScale.setObjectName(u"lblScale")
        self.lblScale.setGeometry(QRect(10, 100, 210, 30))
        self.lblScale.setMinimumSize(QSize(210, 30))
        self.dsbScale = QDoubleSpinBox(self.groupBox)
        self.dsbScale.setObjectName(u"dsbScale")
        self.dsbScale.setGeometry(QRect(240, 100, 70, 30))
        self.dsbScale.setMinimumSize(QSize(70, 30))
        self.btnExportDataMorris = QPushButton(self.groupBox)
        self.btnExportDataMorris.setObjectName(u"btnExportDataMorris")
        self.btnExportDataMorris.setGeometry(QRect(10, 692, 300, 40))
        self.btnExportDataMorris.setMinimumSize(QSize(300, 40))
        self.lblWidthTraj = QLabel(self.groupBox)
        self.lblWidthTraj.setObjectName(u"lblWidthTraj")
        self.lblWidthTraj.setGeometry(QRect(10, 302, 210, 30))
        self.lblWidthTraj.setMinimumSize(QSize(210, 30))
        self.dsblWidthTraj = QDoubleSpinBox(self.groupBox)
        self.dsblWidthTraj.setObjectName(u"dsblWidthTraj")
        self.dsblWidthTraj.setGeometry(QRect(240, 300, 70, 30))
        self.dsblWidthTraj.setMinimumSize(QSize(70, 30))
        self.dsbWidthMarkup = QDoubleSpinBox(self.groupBox)
        self.dsbWidthMarkup.setObjectName(u"dsbWidthMarkup")
        self.dsbWidthMarkup.setGeometry(QRect(240, 340, 70, 30))
        self.dsbWidthMarkup.setMinimumSize(QSize(70, 30))
        self.lblWidthMarkup = QLabel(self.groupBox)
        self.lblWidthMarkup.setObjectName(u"lblWidthMarkup")
        self.lblWidthMarkup.setGeometry(QRect(10, 340, 210, 30))
        self.lblWidthMarkup.setMinimumSize(QSize(210, 30))

        self.gridLayout.addWidget(self.groupBox, 0, 4, 1, 1)


        self.retranslateUi(widgetGraphs)

        QMetaObject.connectSlotsByName(widgetGraphs)
    # setupUi

    def retranslateUi(self, widgetGraphs):
        widgetGraphs.setWindowTitle(QCoreApplication.translate("widgetGraphs", u"Object trajectory map", None))
        self.btnBuildGraph.setText(QCoreApplication.translate("widgetGraphs", u"Build a trajectory graph", None))
        self.btnLoadData.setText(QCoreApplication.translate("widgetGraphs", u"Load data into table", None))
        self.lblTrajectory.setText("")
        self.btnExportDataAll.setText(QCoreApplication.translate("widgetGraphs", u"Download data", None))
        self.btnSaveGraph.setText(QCoreApplication.translate("widgetGraphs", u"Save graph", None))
        self.groupBox.setTitle(QCoreApplication.translate("widgetGraphs", u"Parameters", None))
        self.chbShStEn.setText(QCoreApplication.translate("widgetGraphs", u"Display start and end points", None))
        self.checkbDiveTraj.setText(QCoreApplication.translate("widgetGraphs", u"Display trajectory underwater", None))
        self.chbAddZones.setText(QCoreApplication.translate("widgetGraphs", u"Display zones", None))
        self.lblSpdThFS.setText(QCoreApplication.translate("widgetGraphs", u"Velocity separation threshold, cm/s", None))
        self.lblStopSpdTh.setText(QCoreApplication.translate("widgetGraphs", u"Speed stop threshold, cm/s", None))
        self.lblStopTimeTh.setText(QCoreApplication.translate("widgetGraphs", u"Stop fixation threshold, sec", None))
        self.lblThick.setText(QCoreApplication.translate("widgetGraphs", u"Bridge thickness", None))
        self.chbBuildBr.setText(QCoreApplication.translate("widgetGraphs", u"Build a bridge", None))
        self.lblAngleDist.setText(QCoreApplication.translate("widgetGraphs", u"Angular direction condition, cm", None))
        self.lblAngleTime.setText(QCoreApplication.translate("widgetGraphs", u"Angular direction condition, sec", None))
        self.lblAnglePer.setText(QCoreApplication.translate("widgetGraphs", u"Angular direction condition, %", None))
        self.lblTimeStart.setText(QCoreApplication.translate("widgetGraphs", u"Start time for the training index, sec", None))
        self.lblTimeEnd.setText(QCoreApplication.translate("widgetGraphs", u"End time for the training index, sec", None))
        self.chbWrap.setText(QCoreApplication.translate("widgetGraphs", u"Add zone outlines", None))
        self.lblT0.setText(QCoreApplication.translate("widgetGraphs", u"t0", None))
        self.lblT1.setText(QCoreApplication.translate("widgetGraphs", u"t1", None))
        self.lblT2.setText(QCoreApplication.translate("widgetGraphs", u"t2", None))
        self.lblT3.setText(QCoreApplication.translate("widgetGraphs", u"t3", None))
        self.lblThError.setText(QCoreApplication.translate("widgetGraphs", u"Model error threshold, sec", None))
        self.lblScale.setText(QCoreApplication.translate("widgetGraphs", u"Trajectory graph scale", None))
        self.btnExportDataMorris.setText(QCoreApplication.translate("widgetGraphs", u"Data export", None))
        self.lblWidthTraj.setText(QCoreApplication.translate("widgetGraphs", u"Trajectory line thickness", None))
        self.lblWidthMarkup.setText(QCoreApplication.translate("widgetGraphs", u"Thickness of marking lines", None))
    # retranslateUi

